// <auto-generated />
using System;
using EntityFrameworkSample.DB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkSample.DB.Migrations.Sqlite
{
    [DbContext(typeof(ModelsDbContext_Sqlite))]
    [Migration("20240403023155_ForeignKeySpeedTest")]
    partial class ForeignKeySpeedTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.20");

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest1_Blog", b =>
                {
                    b.Property<long>("idTest1Blog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idTest1Blog");

                    b.ToTable("ForeignKeyTest1_Blog");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest1_Post", b =>
                {
                    b.Property<long>("idTest1Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Int")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("idTest1Blog")
                        .HasColumnType("INTEGER");

                    b.HasKey("idTest1Post");

                    b.HasIndex("idTest1Blog");

                    b.ToTable("ForeignKeyTest1_Post");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest2_Blog", b =>
                {
                    b.Property<long>("idTest2Blog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idTest2Blog");

                    b.ToTable("ForeignKeyTest2_Blog");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest2_Post", b =>
                {
                    b.Property<long>("idTest2Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ForeignKeyTest2_BlogidTest2Blog")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("idTest2Blog")
                        .HasColumnType("INTEGER");

                    b.HasKey("idTest2Post");

                    b.HasIndex("ForeignKeyTest2_BlogidTest2Blog");

                    b.ToTable("ForeignKeyTest2_Post");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest3_Blog", b =>
                {
                    b.Property<long>("idTest3Blog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idTest3Blog");

                    b.ToTable("ForeignKeyTest3_Blog");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest3_Post", b =>
                {
                    b.Property<long>("idTest3Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Int")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("idTest3Blog")
                        .HasColumnType("INTEGER");

                    b.HasKey("idTest3Post");

                    b.HasIndex("idTest3Blog");

                    b.ToTable("ForeignKeyTest3_Post");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.TestOC1", b =>
                {
                    b.Property<int>("idTestOC1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("idTestOC1");

                    b.ToTable("TestOC1");

                    b.HasData(
                        new
                        {
                            idTestOC1 = 1,
                            Int = 1,
                            Str = "str 1",
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.TestOC2", b =>
                {
                    b.Property<int>("idTestOC2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("idTestOC2");

                    b.ToTable("TestOC2");

                    b.HasData(
                        new
                        {
                            idTestOC2 = 1,
                            Int = 2,
                            Str = "str 2"
                        },
                        new
                        {
                            idTestOC2 = 2,
                            Int = 22,
                            Str = "str 22"
                        });
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.TestOC3", b =>
                {
                    b.Property<int>("idTestOC3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("idTestOC3");

                    b.ToTable("TestOC3");

                    b.HasData(
                        new
                        {
                            idTestOC3 = 1,
                            Int = 3,
                            Str = "str 3"
                        });
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest1_Post", b =>
                {
                    b.HasOne("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest1_Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("idTest1Blog")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest2_Post", b =>
                {
                    b.HasOne("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest2_Blog", null)
                        .WithMany("Posts")
                        .HasForeignKey("ForeignKeyTest2_BlogidTest2Blog");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest3_Post", b =>
                {
                    b.HasOne("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest3_Blog", "Blog3")
                        .WithMany("Test3Post")
                        .HasForeignKey("idTest3Blog")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog3");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest1_Blog", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest2_Blog", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.ForeignKeySpeedTest.ForeignKeyTest3_Blog", b =>
                {
                    b.Navigation("Test3Post");
                });
#pragma warning restore 612, 618
        }
    }
}
