// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelsDB;

#nullable disable

namespace ForeignKeyTest.Migrations.Mssql
{
    [DbContext(typeof(ModelsDbContext_Mssql))]
    [Migration("20230830085835_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ModelsDB.Test1Blog", b =>
                {
                    b.Property<long>("idTest1Blog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idTest1Blog"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTest1Blog");

                    b.ToTable("Test1Blog");
                });

            modelBuilder.Entity("ModelsDB.Test1Post", b =>
                {
                    b.Property<long>("idTest1Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idTest1Post"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Int")
                        .HasColumnType("int");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("idTest1Blog")
                        .HasColumnType("bigint");

                    b.HasKey("idTest1Post");

                    b.HasIndex("idTest1Blog");

                    b.ToTable("Test1Post");
                });

            modelBuilder.Entity("ModelsDB.Test2Blog", b =>
                {
                    b.Property<long>("idTest2Blog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idTest2Blog"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTest2Blog");

                    b.ToTable("Test2Blog");
                });

            modelBuilder.Entity("ModelsDB.Test2Post", b =>
                {
                    b.Property<long>("idTest2Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idTest2Post"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Int")
                        .HasColumnType("int");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Test2BlogidTest2Blog")
                        .HasColumnType("bigint");

                    b.Property<long>("idTest2Blog")
                        .HasColumnType("bigint");

                    b.HasKey("idTest2Post");

                    b.HasIndex("Test2BlogidTest2Blog");

                    b.ToTable("Test2Post");
                });

            modelBuilder.Entity("ModelsDB.Test1Post", b =>
                {
                    b.HasOne("ModelsDB.Test1Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("idTest1Blog")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("ModelsDB.Test2Post", b =>
                {
                    b.HasOne("ModelsDB.Test2Blog", null)
                        .WithMany("Posts")
                        .HasForeignKey("Test2BlogidTest2Blog");
                });

            modelBuilder.Entity("ModelsDB.Test1Blog", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ModelsDB.Test2Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
