// <auto-generated />
using EntityFrameworkSample.DB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForeignKeyTest.Migrations.Mssql
{
    [DbContext(typeof(ModelsDbContext_Mssql))]
    partial class ModelsDbContext_MssqlModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test1", b =>
                {
                    b.Property<long>("idAutoIncreases_Test1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idAutoIncreases_Test1"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idAutoIncreases_Test1");

                    b.ToTable("AutoIncreases_Test1");

                    b.HasData(
                        new
                        {
                            idAutoIncreases_Test1 = 1L,
                            Name = "Test"
                        });
                });

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test2", b =>
                {
                    b.Property<long>("idAutoIncreases_Test2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idAutoIncreases_Test2"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("idAutoIncreases_Test1")
                        .HasColumnType("bigint");

                    b.HasKey("idAutoIncreases_Test2");

                    b.HasIndex("idAutoIncreases_Test1");

                    b.ToTable("AutoIncreases_Test2");
                });

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test3", b =>
                {
                    b.Property<long>("idAutoIncreases_Test3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idAutoIncreases_Test3"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("idAutoIncreases_Test1")
                        .HasColumnType("bigint");

                    b.HasKey("idAutoIncreases_Test3");

                    b.HasIndex("idAutoIncreases_Test1");

                    b.ToTable("AutoIncreases_Test3");
                });

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test2", b =>
                {
                    b.HasOne("ForeignKeyTest.TableModels.AutoIncreases_Test1", "Test1")
                        .WithMany("Test2")
                        .HasForeignKey("idAutoIncreases_Test1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test1");
                });

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test3", b =>
                {
                    b.HasOne("ForeignKeyTest.TableModels.AutoIncreases_Test1", "Test1")
                        .WithMany("Test3")
                        .HasForeignKey("idAutoIncreases_Test1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test1");
                });

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test1", b =>
                {
                    b.Navigation("Test2");

                    b.Navigation("Test3");
                });
#pragma warning restore 612, 618
        }
    }
}
