// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using ModelsDB;

#nullable disable

namespace EntityFrameworkSample.DB.MigrationFile.Migrations.Sqlite
{
    [DbContext(typeof(ModelsDbContext_Sqlite))]
    [Migration("20240416014152_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.20");

            modelBuilder.Entity("EntityFrameworkSample.DB.Models.TestTable", b =>
                {
                    b.Property<int>("idTestTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("idTestTable");

                    b.ToTable("TestTable");

                    b.HasData(
                        new
                        {
                            idTestTable = -1,
                            Int = 0,
                            Str = "str 0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
