// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelsDB;

#nullable disable

namespace EntityFrameworkSample.DB.MigrationFile.Migrations.Mariadb
{
    [DbContext(typeof(ModelsDbContext_Mariadb))]
    partial class ModelsDbContext_MariadbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityFrameworkSample.DB.MigrationFile.TableModels.TestTable", b =>
                {
                    b.Property<int>("idTestTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Int")
                        .HasColumnType("int");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("idTestTable");

                    b.ToTable("TestTable");

                    b.HasData(
                        new
                        {
                            idTestTable = -1,
                            Int = 0,
                            Str = "str 0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
