// <auto-generated />
using EntityFrameworkSample.DB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForeignKeyTest.Migrations.Sqlite
{
    [DbContext(typeof(ModelsDbContext_Sqlite))]
    [Migration("20240416094935_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.20");

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test1", b =>
                {
                    b.Property<long>("idAutoIncreases_Test1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idAutoIncreases_Test1");

                    b.ToTable("AutoIncreases_Test1");

                    b.HasData(
                        new
                        {
                            idAutoIncreases_Test1 = 1L,
                            Name = "Test"
                        });
                });

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test2", b =>
                {
                    b.Property<long>("idAutoIncreases_Test2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("idAutoIncreases_Test1")
                        .HasColumnType("INTEGER");

                    b.HasKey("idAutoIncreases_Test2");

                    b.HasIndex("idAutoIncreases_Test1");

                    b.ToTable("AutoIncreases_Test2");
                });

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test3", b =>
                {
                    b.Property<long>("idAutoIncreases_Test3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("idAutoIncreases_Test1")
                        .HasColumnType("INTEGER");

                    b.HasKey("idAutoIncreases_Test3");

                    b.HasIndex("idAutoIncreases_Test1");

                    b.ToTable("AutoIncreases_Test3");
                });

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test2", b =>
                {
                    b.HasOne("ForeignKeyTest.TableModels.AutoIncreases_Test1", "Test1")
                        .WithMany("Test2")
                        .HasForeignKey("idAutoIncreases_Test1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test1");
                });

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test3", b =>
                {
                    b.HasOne("ForeignKeyTest.TableModels.AutoIncreases_Test1", "Test1")
                        .WithMany("Test3")
                        .HasForeignKey("idAutoIncreases_Test1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test1");
                });

            modelBuilder.Entity("ForeignKeyTest.TableModels.AutoIncreases_Test1", b =>
                {
                    b.Navigation("Test2");

                    b.Navigation("Test3");
                });
#pragma warning restore 612, 618
        }
    }
}
